[package]
name = "æ_swap"
version = "0.1.0"
authors = ["Near Inc <hello@near.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
near-sdk = "4.0.0-pre.9"
near-contract-standards = "4.0.0-pre.9"



